l_english: 
 message_settings_tab_settings: "การตั้งค่า"
 message_settings_tab_log: "บันทึกข้อความ"

 MESSAGE_SETTINGS_WINDOW_NAME: "การตั้งค่าข้อความ"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I คลิกเพื่อเปิดการตั้งค่าข้อความ#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nแก้ไขความถี่และการแสดงผลข้อความตามกลุ่มที่กรอง"
 MESSAGE_SETTINGS_WINDOW_RESET: "คืนค่าเริ่มต้น"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T คืนค่าการตั้งค่าข้อความ#!\n#I คลิกเพื่อคืนค่าการเปลี่ยนแปลงปัจจุบันเป็นการตั้งค่าเริ่มต้น#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "ใช้การเปลี่ยนแปลง"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I คลิกเพื่อปิดหน้าต่างการตั้งค่าข้อความและบันทึกการเปลี่ยนแปลงปัจจุบัน#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! ฟีด"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! แจ้งเตือน"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! หน้าต่างแจ้งเตือน"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! ไม่แสดง"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "กลุ่มตัวกรอง"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "ชื่อของกลุ่มตัวกรองข้อความ"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "ลักษณะการแสดงผล"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "วิธีการแสดงข้อความของกลุ่มตัวกรองนี้"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "หยุดชั่วคราว"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "ว่าเกมควรหยุดชั่วคราวหรือไม่เมื่อข้อความของตัวกรองนี้ปรากฏขึ้น"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T สลับการหยุดชั่วคราวอัตโนมัติ#!\n#I สลับเพื่อหยุดเกมชั่วคราวเมื่อข้อความของตัวกรองนี้ปรากฏขึ้น#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T ปิดข้อความ#!\n#I คลิกเพื่อปิดข้อความปัจจุบันและแสดงข้อความถัดไปในคิว#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "ข้อความกำหนดเอง"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T ข้อความกำหนดเอง#!\n#I คลิกเพื่อเขียนข้อความกำหนดเองถึงตัวท่านเองและเลือกเวลาที่ต้องการรับ#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "วันที่มาถึง: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "หัวข้อ:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "คำอธิบาย:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "ทิ้ง"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T ทิ้งข้อความ#!\n#I คลิกเพื่อทิ้งข้อความปัจจุบัน#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "ส่ง"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T ส่ง#!\n#I คลิกเพื่อส่งข้อความปัจจุบัน#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "วัน"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "เดือน"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "ปี"
