l_english: 
 SETTING_DEBUG_SAVES:0 "จำนวนการบันทึกดีบัก"
 SETTING_TUTORIAL:0 "บทช่วยสอน"
 SETTING_DISABLED_HINTS:0 "คำใบ้ที่ปิดใช้งาน"
 #SETTING_FOCUS_ON_COMBAT:1 "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY:1 "ความล่าช้าของคำแนะนำเครื่องมือ"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nตั้งค่าความล่าช้าก่อนที่คำแนะนำเครื่องมือจะปรากฏ"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "ความล่าช้าในการปลดล็อก"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nตั้งค่าความล่าช้าก่อนที่คำแนะนำเครื่องมือจะถูกปลดล็อก"
 SETTING_TOOLTIP_LOCK_TIME:0 "ความล่าช้าในการล็อก"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nตั้งค่าความล่าช้าก่อนที่คำแนะนำเครื่องมือจะถูกล็อก"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "ความล่าช้าในการเปิดเมื่อถูกล็อก"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nตั้งค่าความล่าช้าก่อนที่คำแนะนำเครื่องมือจะถูกล็อกเมื่อมีคำแนะนำเครื่องมืออื่นเปิดอยู่แล้ว"
 # Audio
 SETTING_Sound_Effects:1 "เสียงประกอบทั้งหมด"
 SETTING_Sound_Effects_TOOLTIP:1 "#T ระดับเสียงประกอบ\n#!ตั้งค่าระดับเสียงของเสียงประกอบทั้งหมด"
 SETTING_Ambience:0 "เสียงบรรยากาศ"
 SETTING_Ambience_TOOLTIP:1 "#T ระดับเสียงบรรยากาศ\n#!ตั้งค่าระดับเสียงของเสียงบรรยากาศแวดล้อม"
 SETTING_TOOLTIP_MODE:1 "โหมดคำแนะนำเครื่องมือ"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nตั้งค่าวิธีที่คำแนะนำเครื่องมือ "ล็อกเข้าที่" ทำให้สามารถใช้คำแนะนำเครื่องมือซ้อนคำแนะนำเครื่องมือได้"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "ตามแนวโน้มเมาส์"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nคำแนะนำเครื่องมือจะล็อกเข้าที่โดยอัตโนมัติจนกว่าเคอร์เซอร์จะเลื่อนออกไป"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "ล็อกด้วยการกระทำ"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nกด #V ปุ่มกลางเมาส์#! เพื่อล็อกและปลดล็อกคำแนะนำเครื่องมือ"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "ล็อกด้วยตัวจับเวลา"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nคำแนะนำเครื่องมือจะถูกล็อกเข้าที่หากเคอร์เซอร์ไม่เคลื่อนที่เป็นเวลาสั้นๆ #weak (การตั้งค่าเริ่มต้น)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "เบ็ดเตล็ด"
 SETTINGS_CATEGORY_TOOLTIPS:0 "คำแนะนำเครื่องมือ"
 SETTINGS_CATEGORY_SFX:0 "เสียงประกอบเฉพาะ"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "ทั่วไป"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "การควบคุมแผนที่"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "การบันทึกเกม"
 SETTINGS_CATEGORY_LANGUAGE:0 "ภาษา"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "ขั้นสูง – ทั่วไป"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "ขั้นสูง – แผนที่"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "ขั้นสูง – ตัวละคร"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "ภาพเหมือน"
 SETTINGS_CATEGORY_GAME_EVENTS: "เหตุการณ์"
 SETTINGS_CATEGORY_GAME_FLAVOR:0 "อรรถรส"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "ผู้เล่นหลายคน"
 SETTINGS_CATEGORY_MAP:0 "แผนที่"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "แสดงโรคและการบาดเจ็บที่เห็นภาพชัดเจน"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nตั้งค่าว่าจะให้การบาดเจ็บและโรคที่เห็นภาพชัดเจนปรากฏบนภาพเหมือนตัวละครหรือไม่"
 SETTING_SHOW_NUDITY:0 "แสดงภาพเปลือย"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nตั้งค่าว่าจะสามารถแสดงตัวละครในสภาพเปลือยได้หรือไม่"
 SETTINGS_CATEGORY_GAME_DLC_MODS:0 "เนื้อหาดาวน์โหลดได้"
 SETTING_SHOW_CONTENT_SOURCE:0 "แสดง DLC ของเหตุการณ์"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP:0 "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nตั้งค่าว่าเหตุการณ์จะแสดงว่ามาจาก DLC ใด"

 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "การแพนกล้องเมื่อไม่ใช้งานในราชสำนัก"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nกำหนดว่ากล้องในราชสำนักควรแพนเบาๆ ไปทั่วราชสำนักของท่านเมื่อไม่ใช้งานหรือไม่\n\nหากปิดใช้งานตัวละครเคลื่อนไหว การตั้งค่านี้จะไม่มีผล"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "การเปลี่ยนผ่านที่ราบรื่นในราชสำนัก"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nกำหนดว่ากล้องในราชสำนักควรเคลื่อนที่ไปยังตำแหน่งใหม่อย่างราบรื่นหรือไม่\n\nหากปิดใช้งานตัวละครเคลื่อนไหว การตั้งค่านี้จะไม่มีผล"
 NEVER:0 "ไม่เลย"
 MONTHLY:0 "ทุกเดือน"
 HALFYEAR:0 "ทุก 6 เดือน"
 YEARLY:0 "ทุกปี"
 FIVE_YEAR:0 "ทุก 5 ปี"
 SETTINGS_CATEGORY_TUTORIAL:0 "บทช่วยสอน"
 SETTING_REACTIVE_TUTORIAL:1 "แสดงคำแนะนำเชิงตอบสนอง"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nตั้งค่าว่าเกมควรแสดงคำแนะนำบทช่วยสอนที่ตอบสนองต่อวิธีการเล่นของท่านหรือไม่ มีประโยชน์สำหรับผู้เล่นใหม่ของ Crusader Kings III"
 SETTING_SHOW_SUGGESTIONS:0 "แสดงข้อเสนอแนะ"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nตั้งค่าว่าเกมควรเสนอแนะสิ่งที่ต้องทำเป็นระยะๆ หรือไม่ มีประโยชน์สำหรับผู้เล่นใหม่ของ Crusader Kings III"
 RESET_REACTIVE_ADVICE:0 "รีเซ็ตคำแนะนำเชิงตอบสนอง"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T รีเซ็ตคำแนะนำเชิงตอบสนอง#!\nคำแนะนำเชิงตอบสนองที่เคยเห็นก่อนหน้านี้จะปรากฏขึ้นอีกครั้ง"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "รีเซ็ตคำแนะนำเชิงตอบสนอง"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "ท่านแน่ใจหรือไม่ว่าต้องการรีเซ็ตคำแนะนำเชิงตอบสนอง?"
 SETTING_ADVANCED_SHADERS:0 "เอฟเฟกต์เชดเดอร์ขั้นสูง"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T เอฟเฟกต์เชดเดอร์ขั้นสูง\n#!ตัวเลือกนี้จะเปิดใช้งานเอฟเฟกต์เชดเดอร์ขั้นสูง\n\nการปิดใช้งานอาจเพิ่มประสิทธิภาพ แต่แลกมาด้วยการ ทำให้เอฟเฟกต์บางอย่าง ( เช่น ภูมิประเทศและน้ำ) ดูแย่ลง"
 SETTING_WINTER_PARTICLE_EFFECTS:0 "เอฟเฟกต์อนุภาคฤดูหนาว"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nกำหนดว่าจะแสดงเอฟเฟกต์อนุภาคหรือไม่เมื่อฤดูหนาวมีผลในบางพื้นที่ของแผนที่\n\nการปิดใช้งานอาจเพิ่มประสิทธิภาพ"
 SETTING_RESET_CAMERA_ROTATION:0 "รีเซ็ตการหมุนกล้อง"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nกำหนดว่ากล้องควรรีเซ็ตตำแหน่งเริ่มต้นโดยอัตโนมัติหลังจากผู้ใช้หมุนหรือไม่"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "เอียงกล้องเมื่อซูมออก"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nกำหนดว่ากล้องควรเอียงไปยังค่าเอียงเริ่มต้นเมื่อซูมออกหรือไม่"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "ตัวละครพื้นหลังในฉากราชสำนัก"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nกำหนดว่าฉาก 3 มิติของราชสำนักควรแสดงตัวละครพื้นหลังที่ไม่สำคัญหรือไม่"
 SETTING_MAP_HIGHLIGHT:0 "แสงเน้นเคอร์เซอร์บนแผนที่"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\nกำหนดความเข้มของแสงเน้นเคอร์เซอร์บนแผนที่"
 SETTING_MAP_OVERLORD_HIGHLIGHT: "การเน้นเจ้าเหนือหัวบนแผนที่"
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\nกำหนดว่าจะเน้นเจ้าเหนือหัวสูงสุดของอาณาจักรเมื่อใด ขณะเลือกอาณาจักร"
 OPTION_ALWAYS: "เสมอ"
 OPTION_TRIBUTARY_ONLY: "เฉพาะรัฐบรรณาการ"
 BASED_ON_ZOOM_LEVEL:0 "ไดนามิก"
 ALWAYS_HIDE:0 "ซ่อนเสมอ"
 ALWAYS_SHOW:0 "แสดงเสมอ"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "เส้นขอบชายฝั่ง"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nตัวเลือกนี้จะควบคุมว่าจะแสดงเส้นขอบอาณาจักรบริเวณชายฝั่งเมื่อใด\nหากตั้งค่าเป็น $BASED_ON_ZOOM_LEVEL$ เส้นขอบจะถูกซ่อนในระดับการซูมละเอียด\n\nการเลือก $ALWAYS_SHOW$ หรือ $ALWAYS_HIDE$ อาจช่วยเพิ่มประสิทธิภาพของเกม แต่ต้องแลกมากับการที่เส้นขอบอาณาจักรชายฝั่งจะไม่ซ่อนแบบไดนามิก"
 SETTINGS_DISCARD_CHANGES:0 "ยกเลิกการเปลี่ยนแปลง"
 ONLY_TOOLTIPS: "เฉพาะในคำแนะนำเครื่องมือ"
 OPTIONS_AND_TOOLTIPS: "ในตัวเลือกและคำแนะนำเครื่องมือ"
 NOWHERE: "ไม่มีที่ไหนเลย"
 SETTING_SHOW_EVENT_SHORTCUTS: "แสดงคีย์ลัดสำหรับตัวเลือกเหตุการณ์"
 SETTING_SHOW_EVENT_SHORTCUTS_TOOLTIP: "#T $SETTING_SHOW_EVENT_SHORTCUTS$#!\nตั้งค่าสถานที่แสดงหมายเลขคีย์ลัดสำหรับตัวเลือกเหตุการณ์ต่างๆ\nคีย์ลัด:\n#i กด Shift+หมายเลข เพื่อเลือกตัวเลือก\nกด Alt+หมายเลข เพื่อดูตัวอย่างและยืนยันหนึ่งตัวเลือก\nกด Alt+E เพื่อดูตัวอย่างตัวเลือกทั้งหมด#!"
 SETTING_HUD_SKIN:0 "สกิน HUD"
 hud_skin_auto:0 "ไดนามิก"
 default:0 "ค่าเริ่มต้น"
 iberian:0 "ไอบีเรียน"
 Norse:0 "นอร์ส"
 byzantine: "ไบแซนไทน์"
 iranian: "@legacyofpersia_icon! มรดกแห่งเปอร์เซีย"
 nomad: "@khansofthesteppe_icon! ข่านแห่งทุ่งหญ้าสเตปป์"
 asia: "@allunderheaven_icon! ใต้หล้า"
 SETTING_HUD_SKIN_TOOLTIP:0 "#T $SETTING_HUD_SKIN$#!\nตั้งค่าธีมภาพของส่วนติดต่อผู้ใช้ HUD - UI 2 มิติที่แสดงบนหน้าจอเกมหลัก\n\nหากเลือก $hud_skin_auto$ HUD จะเปลี่ยนไปตามวัฒนธรรม ศรัทธา และเมืองหลวงของอาณาจักรของผู้เล่น"
 SETTING_RICH_PRESENCE:0 "การแสดงสถานะแบบละเอียด"
 SETTING_RICH_PRESENCE_TOOLTIP:0 "#T $SETTING_RICH_PRESENCE$#!\nแสดงข้อมูลเกี่ยวกับเซสชันการเล่นปัจจุบันของคุณให้เพื่อนๆ ทราบหากแพลตฟอร์มของคุณรองรับ"
 SETTING_USE_DYNASTY_NAMED_REALMS:0 "อาณาจักรที่ตั้งชื่อตามราชวงศ์"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP:0 "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nบางวัฒนธรรมจะตั้งชื่อบรรดาศักดิ์หลักตามราชวงศ์ของตน ( เช่น: อับบาซิด)"
 map_table_style_auto: "ไดนามิก"
 map_table_style_western: "ค่าเริ่มต้น"
 map_table_style_ce1: "โรคระบาด"
 map_table_style_ep3: "ไบแซนไทน์"
 map_table_style_tgp: "@allunderheaven_icon! ใต้หล้า"
 SETTING_MAP_TABLE_STYLE: "รูปแบบโต๊ะแผนที่"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nตั้งค่ารูปแบบภาพของโต๊ะแผนที่ - แผนที่และสภาพแวดล้อม 3 มิติที่แสดงเมื่อซูมออก\n\nหากเลือก $map_table_style_auto$ รูปแบบโต๊ะแผนที่จะถูกเลือกตามผู้เล่นปัจจุบันและตัวละครของพวกเขา"
 SETTING_SHOW_EVENT_NAME_PLATES: "แสดงป้ายชื่อเหตุการณ์"
 SETTING_SHOW_EVENT_NAME_PLATES_TOOLTIP: "#T $SETTING_SHOW_EVENT_NAME_PLATES$#!\nแสดงชื่อ ความสัมพันธ์ และความเห็นของตัวละครในเหตุการณ์ต่างๆ\nนอกจากนี้ คำแนะนำเครื่องมือของตัวละครจะปรากฏเหนือป้ายชื่อแทนที่ภาพบุคคลเพื่อการเลือกที่ง่ายขึ้น\nมีผลกับเหตุการณ์ทั่วไปเท่านั้น ไม่สามารถใช้ได้กับการดวลและกิจกรรมต่างๆ"
 SETTINGS_CATEGORY_STYLING: "การจัดรูปแบบส่วนติดต่อผู้ใช้"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "กราฟิกโรค"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nตั้งค่าว่าจะแสดงเอฟเฟกต์โรคบนแผนที่หรือไม่"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "กราฟิกตำนาน"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nตั้งค่าว่าจะแสดงเอฟเฟกต์ตำนานบนแผนที่หรือไม่"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "ไอคอน [raid|E] แบบละเอียด"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nกำหนดว่าไอคอน [raid|E] บนแผนที่ควรแสดงแบบย่อหรือแบบละเอียด\n\n#I หากเปิดใช้งาน กด Alt ค้างไว้เพื่อแสดงที่ดินทั้งหมดพร้อมโภคทรัพย์ที่ท่านสามารถ [raid|E] ได้#!"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "ไอคอน [barter|E] แบบละเอียด"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nกำหนดว่าไอคอน [barter|E] บนแผนที่ควรแสดงแบบย่อหรือแบบละเอียด\n\n#I หากเปิดใช้งาน กด Alt ค้างไว้เพื่อแสดงที่ดินทั้งหมดพร้อมโภคทรัพย์ที่ท่านสามารถ [barter|E] ได้#!"
 SETTING_PAPER_MAP_STYLE: "รูปแบบแผนที่กระดาษ"
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nกำหนดรูปแบบแผนที่ที่จะแสดงเมื่อซูมแผนที่ออก\n\nหากเลือก $paper_map_style_auto$ แผนที่กระดาษจะใช้รูปแบบเดียวกับ \"$SETTING_MAP_TABLE_STYLE$\""
 paper_map_style_auto: "เปลี่ยนแปลงอัตโนมัติ"
 paper_map_style_western: "ค่าเริ่มต้น"
 paper_map_style_tgp: "ใต้หล้า"
 SETTING_ADAPTIVE_FRAMERATE: "อัตราเฟรมแบบปรับได้"
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#!ลดอัตราการอัปเดตหน้าจอหากความเร็วการอัปเดตเกมลดลง เพื่อปรับปรุงประสิทธิภาพการเล่นเกม"
 SETTING_HIDE_MAP_TABLE: "ซ่อนโต๊ะแผนที่"
 SETTING_HIDE_MAP_TABLE_TOOLTIP: "#T $SETTING_HIDE_MAP_TABLE$\n#!ซ่อนรูปทรงของโต๊ะแผนที่"
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "เงาเมฆ"
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\nกำหนดว่าจะแสดงเอฟเฟกต์เงาเมฆบนภูมิประเทศหรือไม่"
 SETTING_HAS_TREE_DITHERING_ENABLED: "การเกลี่ยสีต้นไม้"
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nกำหนดว่าจะใช้เอฟเฟกต์การเกลี่ยสีกับต้นไม้เพื่อ ทำให้ขอบนุ่มนวลขึ้นหรือไม่"
 SETTING_MAP_BRIGHTNESS:0 "ความสว่างแผนที่กระดาษ"
 SETTING_MAP_BRIGHTNESS_TOOLTIP:0 "#T $SETTING_MAP_BRIGHTNESS$#!\nกำหนดความเข้มของความสว่างแผนที่กระดาษ"
